#ifndef POSIX_ALIGN_ERRNO_H
#define POSIX_ALIGN_ERRNO_H

/*
 * POSIX does not give values of errno.
 * We take those already defined for the current system (OS+compiler)
 * and define those missing
 */

#undef  _POSIX_ALIGN_ERRNO_START
#define _POSIX_ALIGN_ERRNO_START 10000

#cmakedefine HAVE_ERRNO_E2BIG           @HAVE_ERRNO_E2BIG@
#cmakedefine HAVE_ERRNO_EACCES          @HAVE_ERRNO_EACCES@
#cmakedefine HAVE_ERRNO_EADDRINUSE      @HAVE_ERRNO_EADDRINUSE@
#cmakedefine HAVE_ERRNO_EADDRNOTAVAIL   @HAVE_ERRNO_EADDRNOTAVAIL@
#cmakedefine HAVE_ERRNO_EAFNOSUPPORT    @HAVE_ERRNO_EAFNOSUPPORT@
#cmakedefine HAVE_ERRNO_EAGAIN          @HAVE_ERRNO_EAGAIN@
#cmakedefine HAVE_ERRNO_EALREADY        @HAVE_ERRNO_EALREADY@
#cmakedefine HAVE_ERRNO_EBADF           @HAVE_ERRNO_EBADF@
#cmakedefine HAVE_ERRNO_EBADMSG         @HAVE_ERRNO_EBADMSG@
#cmakedefine HAVE_ERRNO_EBUSY           @HAVE_ERRNO_EBUSY@
#cmakedefine HAVE_ERRNO_ECANCELED       @HAVE_ERRNO_ECANCELED@
#cmakedefine HAVE_ERRNO_ECHILD          @HAVE_ERRNO_ECHILD@
#cmakedefine HAVE_ERRNO_ECONNABORTED    @HAVE_ERRNO_ECONNABORTED@
#cmakedefine HAVE_ERRNO_ECONNREFUSED    @HAVE_ERRNO_ECONNREFUSED@
#cmakedefine HAVE_ERRNO_ECONNRESET      @HAVE_ERRNO_ECONNRESET@
#cmakedefine HAVE_ERRNO_EDEADLK         @HAVE_ERRNO_EDEADLK@
#cmakedefine HAVE_ERRNO_EDESTADDRREQ    @HAVE_ERRNO_EDESTADDRREQ@
#cmakedefine HAVE_ERRNO_EDOM            @HAVE_ERRNO_EDOM@
#cmakedefine HAVE_ERRNO_EDQUOT          @HAVE_ERRNO_EDQUOT@
#cmakedefine HAVE_ERRNO_EEXIST          @HAVE_ERRNO_EEXIST@
#cmakedefine HAVE_ERRNO_EFAULT          @HAVE_ERRNO_EFAULT@
#cmakedefine HAVE_ERRNO_EFBIG           @HAVE_ERRNO_EFBIG@
#cmakedefine HAVE_ERRNO_EHOSTUNREACH    @HAVE_ERRNO_EHOSTUNREACH@
#cmakedefine HAVE_ERRNO_EIDRM           @HAVE_ERRNO_EIDRM@
#cmakedefine HAVE_ERRNO_EILSEQ          @HAVE_ERRNO_EILSEQ@
#cmakedefine HAVE_ERRNO_EINPROGRESS     @HAVE_ERRNO_EINPROGRESS@
#cmakedefine HAVE_ERRNO_EINTR           @HAVE_ERRNO_EINTR@
#cmakedefine HAVE_ERRNO_EINVAL          @HAVE_ERRNO_EINVAL@
#cmakedefine HAVE_ERRNO_EIO             @HAVE_ERRNO_EIO@
#cmakedefine HAVE_ERRNO_EIO             @HAVE_ERRNO_EIO@
#cmakedefine HAVE_ERRNO_EISCONN         @HAVE_ERRNO_EISCONN@
#cmakedefine HAVE_ERRNO_EISDIR          @HAVE_ERRNO_EISDIR@
#cmakedefine HAVE_ERRNO_ELOOP           @HAVE_ERRNO_ELOOP@
#cmakedefine HAVE_ERRNO_EMFILE          @HAVE_ERRNO_EMFILE@
#cmakedefine HAVE_ERRNO_EMLINK          @HAVE_ERRNO_EMLINK@
#cmakedefine HAVE_ERRNO_EMSGSIZE        @HAVE_ERRNO_EMSGSIZE@
#cmakedefine HAVE_ERRNO_EMULTIHOP       @HAVE_ERRNO_EMULTIHOP@
#cmakedefine HAVE_ERRNO_ENAMETOOLONG    @HAVE_ERRNO_ENAMETOOLONG@
#cmakedefine HAVE_ERRNO_ENETDOWN        @HAVE_ERRNO_ENETDOWN@
#cmakedefine HAVE_ERRNO_ENETRESET       @HAVE_ERRNO_ENETRESET@
#cmakedefine HAVE_ERRNO_ENETUNREACH     @HAVE_ERRNO_ENETUNREACH@
#cmakedefine HAVE_ERRNO_ENFILE          @HAVE_ERRNO_ENFILE@
#cmakedefine HAVE_ERRNO_ENOBUFS         @HAVE_ERRNO_ENOBUFS@
#cmakedefine HAVE_ERRNO_ENODATA         @HAVE_ERRNO_ENODATA@
#cmakedefine HAVE_ERRNO_ENODEV          @HAVE_ERRNO_ENODEV@
#cmakedefine HAVE_ERRNO_ENOENT          @HAVE_ERRNO_ENOENT@
#cmakedefine HAVE_ERRNO_ENOEXEC         @HAVE_ERRNO_ENOEXEC@
#cmakedefine HAVE_ERRNO_ENOLCK          @HAVE_ERRNO_ENOLCK@
#cmakedefine HAVE_ERRNO_ENOLINK         @HAVE_ERRNO_ENOLINK@
#cmakedefine HAVE_ERRNO_ENOMEM          @HAVE_ERRNO_ENOMEM@
#cmakedefine HAVE_ERRNO_ENOMSG          @HAVE_ERRNO_ENOMSG@
#cmakedefine HAVE_ERRNO_ENOPROTOOPT     @HAVE_ERRNO_ENOPROTOOPT@
#cmakedefine HAVE_ERRNO_ENOSPC          @HAVE_ERRNO_ENOSPC@
#cmakedefine HAVE_ERRNO_ENOSR           @HAVE_ERRNO_ENOSR@
#cmakedefine HAVE_ERRNO_ENOSTR          @HAVE_ERRNO_ENOSTR@
#cmakedefine HAVE_ERRNO_ENOSYS          @HAVE_ERRNO_ENOSYS@
#cmakedefine HAVE_ERRNO_ENOTCONN        @HAVE_ERRNO_ENOTCONN@
#cmakedefine HAVE_ERRNO_ENOTDIR         @HAVE_ERRNO_ENOTDIR@
#cmakedefine HAVE_ERRNO_ENOTEMPTY       @HAVE_ERRNO_ENOTEMPTY@
#cmakedefine HAVE_ERRNO_ENOTRECOVERABLE @HAVE_ERRNO_ENOTRECOVERABLE@
#cmakedefine HAVE_ERRNO_ENOTSOCK        @HAVE_ERRNO_ENOTSOCK@
#cmakedefine HAVE_ERRNO_ENOTSUP         @HAVE_ERRNO_ENOTSUP@
#cmakedefine HAVE_ERRNO_ENOTTY          @HAVE_ERRNO_ENOTTY@
#cmakedefine HAVE_ERRNO_ENXIO           @HAVE_ERRNO_ENXIO@
#cmakedefine HAVE_ERRNO_EOPNOTSUPP      @HAVE_ERRNO_EOPNOTSUPP@
#cmakedefine HAVE_ERRNO_EOVERFLOW       @HAVE_ERRNO_EOVERFLOW@
#cmakedefine HAVE_ERRNO_EOWNERDEAD      @HAVE_ERRNO_EOWNERDEAD@
#cmakedefine HAVE_ERRNO_EPERM           @HAVE_ERRNO_EPERM@
#cmakedefine HAVE_ERRNO_EPIPE           @HAVE_ERRNO_EPIPE@
#cmakedefine HAVE_ERRNO_EPROTO          @HAVE_ERRNO_EPROTO@
#cmakedefine HAVE_ERRNO_EPROTONOSUPPORT @HAVE_ERRNO_EPROTONOSUPPORT@
#cmakedefine HAVE_ERRNO_EPROTOTYPE      @HAVE_ERRNO_EPROTOTYPE@
#cmakedefine HAVE_ERRNO_ERANGE          @HAVE_ERRNO_ERANGE@
#cmakedefine HAVE_ERRNO_EROFS           @HAVE_ERRNO_EROFS@
#cmakedefine HAVE_ERRNO_ESPIPE          @HAVE_ERRNO_ESPIPE@
#cmakedefine HAVE_ERRNO_ESRCH           @HAVE_ERRNO_ESRCH@
#cmakedefine HAVE_ERRNO_ESTALE          @HAVE_ERRNO_ESTALE@
#cmakedefine HAVE_ERRNO_ETIME           @HAVE_ERRNO_ETIME@
#cmakedefine HAVE_ERRNO_ETIMEDOUT       @HAVE_ERRNO_ETIMEDOUT@
#cmakedefine HAVE_ERRNO_ETXTBSY         @HAVE_ERRNO_ETXTBSY@
#cmakedefine HAVE_ERRNO_EWOULDBLOCK     @HAVE_ERRNO_EWOULDBLOCK@
#cmakedefine HAVE_ERRNO_EXDEV           @HAVE_ERRNO_EXDEV@

#ifndef E2BIG
#define E2BIG (_POSIX_ALIGN_ERRNO_START+1)
#endif
#ifndef EACCES
#define EACCES (_POSIX_ALIGN_ERRNO_START+2)
#endif
#ifndef EADDRINUSE
#define EADDRINUSE (_POSIX_ALIGN_ERRNO_START+3)
#endif
#ifndef EADDRNOTAVAIL
#define EADDRNOTAVAIL (_POSIX_ALIGN_ERRNO_START+4)
#endif
#ifndef EAFNOSUPPORT
#define EAFNOSUPPORT (_POSIX_ALIGN_ERRNO_START+5)
#endif
#ifndef EAGAIN
#define EAGAIN (_POSIX_ALIGN_ERRNO_START+6)
#endif
#ifndef EALREADY
#define EALREADY (_POSIX_ALIGN_ERRNO_START+7)
#endif
#ifndef EBADF
#define EBADF (_POSIX_ALIGN_ERRNO_START+8)
#endif
#ifndef EBADMSG
#define EBADMSG (_POSIX_ALIGN_ERRNO_START+9)
#endif
#ifndef EBUSY
#define EBUSY (_POSIX_ALIGN_ERRNO_START+10)
#endif
#ifndef ECANCELED
#define ECANCELED (_POSIX_ALIGN_ERRNO_START+11)
#endif
#ifndef ECHILD
#define ECHILD (_POSIX_ALIGN_ERRNO_START+12)
#endif
#ifndef ECONNABORTED
#define ECONNABORTED (_POSIX_ALIGN_ERRNO_START+13)
#endif
#ifndef ECONNREFUSED
#define ECONNREFUSED (_POSIX_ALIGN_ERRNO_START+14)
#endif
#ifndef ECONNRESET
#define ECONNRESET (_POSIX_ALIGN_ERRNO_START+15)
#endif
#ifndef EDEADLK
#define EDEADLK (_POSIX_ALIGN_ERRNO_START+16)
#endif
#ifndef EDESTADDRREQ
#define EDESTADDRREQ (_POSIX_ALIGN_ERRNO_START+17)
#endif
#ifndef EDOM
#define EDOM (_POSIX_ALIGN_ERRNO_START+18)
#endif
#ifndef EDQUOT
#define EDQUOT (_POSIX_ALIGN_ERRNO_START+19)
#endif
#ifndef EEXIST
#define EEXIST (_POSIX_ALIGN_ERRNO_START+20)
#endif
#ifndef EFAULT
#define EFAULT (_POSIX_ALIGN_ERRNO_START+21)
#endif
#ifndef EFBIG
#define EFBIG (_POSIX_ALIGN_ERRNO_START+22)
#endif
#ifndef EHOSTUNREACH
#define EHOSTUNREACH (_POSIX_ALIGN_ERRNO_START+23)
#endif
#ifndef EIDRM
#define EIDRM (_POSIX_ALIGN_ERRNO_START+24)
#endif
#ifndef EILSEQ
#define EILSEQ (_POSIX_ALIGN_ERRNO_START+25)
#endif
#ifndef EINPROGRESS
#define EINPROGRESS (_POSIX_ALIGN_ERRNO_START+26)
#endif
#ifndef EINTR
#define EINTR (_POSIX_ALIGN_ERRNO_START+27)
#endif
#ifndef EINVAL
#define EINVAL (_POSIX_ALIGN_ERRNO_START+28)
#endif
#ifndef EIO
#define EIO (_POSIX_ALIGN_ERRNO_START+29)
#endif
#ifndef EIO
#define EIO (_POSIX_ALIGN_ERRNO_START+30)
#endif
#ifndef EISCONN
#define EISCONN (_POSIX_ALIGN_ERRNO_START+31)
#endif
#ifndef EISDIR
#define EISDIR (_POSIX_ALIGN_ERRNO_START+32)
#endif
#ifndef ELOOP
#define ELOOP (_POSIX_ALIGN_ERRNO_START+33)
#endif
#ifndef EMFILE
#define EMFILE (_POSIX_ALIGN_ERRNO_START+34)
#endif
#ifndef EMLINK
#define EMLINK (_POSIX_ALIGN_ERRNO_START+35)
#endif
#ifndef EMSGSIZE
#define EMSGSIZE (_POSIX_ALIGN_ERRNO_START+36)
#endif
#ifndef EMULTIHOP
#define EMULTIHOP (_POSIX_ALIGN_ERRNO_START+37)
#endif
#ifndef ENAMETOOLONG
#define ENAMETOOLONG (_POSIX_ALIGN_ERRNO_START+38)
#endif
#ifndef ENETDOWN
#define ENETDOWN (_POSIX_ALIGN_ERRNO_START+39)
#endif
#ifndef ENETRESET
#define ENETRESET (_POSIX_ALIGN_ERRNO_START+40)
#endif
#ifndef ENETUNREACH
#define ENETUNREACH (_POSIX_ALIGN_ERRNO_START+41)
#endif
#ifndef ENFILE
#define ENFILE (_POSIX_ALIGN_ERRNO_START+42)
#endif
#ifndef ENOBUFS
#define ENOBUFS (_POSIX_ALIGN_ERRNO_START+43)
#endif
#ifndef ENODATA
#define ENODATA (_POSIX_ALIGN_ERRNO_START+44)
#endif
#ifndef ENODEV
#define ENODEV (_POSIX_ALIGN_ERRNO_START+45)
#endif
#ifndef ENOENT
#define ENOENT (_POSIX_ALIGN_ERRNO_START+46)
#endif
#ifndef ENOEXEC
#define ENOEXEC (_POSIX_ALIGN_ERRNO_START+47)
#endif
#ifndef ENOLCK
#define ENOLCK (_POSIX_ALIGN_ERRNO_START+48)
#endif
#ifndef ENOLINK
#define ENOLINK (_POSIX_ALIGN_ERRNO_START+49)
#endif
#ifndef ENOMEM
#define ENOMEM (_POSIX_ALIGN_ERRNO_START+50)
#endif
#ifndef ENOMSG
#define ENOMSG (_POSIX_ALIGN_ERRNO_START+51)
#endif
#ifndef ENOPROTOOPT
#define ENOPROTOOPT (_POSIX_ALIGN_ERRNO_START+52)
#endif
#ifndef ENOSPC
#define ENOSPC (_POSIX_ALIGN_ERRNO_START+53)
#endif
#ifndef ENOSR
#define ENOSR (_POSIX_ALIGN_ERRNO_START+54)
#endif
#ifndef ENOSTR
#define ENOSTR (_POSIX_ALIGN_ERRNO_START+55)
#endif
#ifndef ENOSYS
#define ENOSYS (_POSIX_ALIGN_ERRNO_START+56)
#endif
#ifndef ENOTCONN
#define ENOTCONN (_POSIX_ALIGN_ERRNO_START+57)
#endif
#ifndef ENOTDIR
#define ENOTDIR (_POSIX_ALIGN_ERRNO_START+58)
#endif
#ifndef ENOTEMPTY
#define ENOTEMPTY (_POSIX_ALIGN_ERRNO_START+59)
#endif
#ifndef ENOTRECOVERABLE
#define ENOTRECOVERABLE (_POSIX_ALIGN_ERRNO_START+60)
#endif
#ifndef ENOTSOCK
#define ENOTSOCK (_POSIX_ALIGN_ERRNO_START+61)
#endif
#ifndef ENOTSUP
#define ENOTSUP (_POSIX_ALIGN_ERRNO_START+62)
#endif
#ifndef ENOTTY
#define ENOTTY (_POSIX_ALIGN_ERRNO_START+63)
#endif
#ifndef ENXIO
#define ENXIO (_POSIX_ALIGN_ERRNO_START+64)
#endif
#ifndef EOPNOTSUPP
#define EOPNOTSUPP (_POSIX_ALIGN_ERRNO_START+65)
#endif
#ifndef EOVERFLOW
#define EOVERFLOW (_POSIX_ALIGN_ERRNO_START+66)
#endif
#ifndef EOWNERDEAD
#define EOWNERDEAD (_POSIX_ALIGN_ERRNO_START+67)
#endif
#ifndef EPERM
#define EPERM (_POSIX_ALIGN_ERRNO_START+68)
#endif
#ifndef EPIPE
#define EPIPE (_POSIX_ALIGN_ERRNO_START+69)
#endif
#ifndef EPROTO
#define EPROTO (_POSIX_ALIGN_ERRNO_START+70)
#endif
#ifndef EPROTONOSUPPORT
#define EPROTONOSUPPORT (_POSIX_ALIGN_ERRNO_START+71)
#endif
#ifndef EPROTOTYPE
#define EPROTOTYPE (_POSIX_ALIGN_ERRNO_START+72)
#endif
#ifndef ERANGE
#define ERANGE (_POSIX_ALIGN_ERRNO_START+73)
#endif
#ifndef EROFS
#define EROFS (_POSIX_ALIGN_ERRNO_START+74)
#endif
#ifndef ESPIPE
#define ESPIPE (_POSIX_ALIGN_ERRNO_START+75)
#endif
#ifndef ESRCH
#define ESRCH (_POSIX_ALIGN_ERRNO_START+76)
#endif
#ifndef ESTALE
#define ESTALE (_POSIX_ALIGN_ERRNO_START+77)
#endif
#ifndef ETIME
#define ETIME (_POSIX_ALIGN_ERRNO_START+78)
#endif
#ifndef ETIMEDOUT
#define ETIMEDOUT (_POSIX_ALIGN_ERRNO_START+79)
#endif
#ifndef ETXTBSY
#define ETXTBSY (_POSIX_ALIGN_ERRNO_START+80)
#endif
#ifndef EWOULDBLOCK
#define EWOULDBLOCK (_POSIX_ALIGN_ERRNO_START+81)
#endif
#ifndef EXDEV
#define EXDEV (_POSIX_ALIGN_ERRNO_START+82)
#endif

#endif /* POSIX_ALIGN_ERRNO_H */
